export const OPEN_OVERLAY = "OPEN_OVERLAY";
export const CHANGE_TYPE = "CHANGE_TYPE";
export const ADD_FIELD = "ADD_FIELD";
export const REMOVE_FIELD = "REMOVE _FIELD";
export const CHANGE_VALUE = "CHANGE_VALUE";
export const CHANGE_LABEL = "CHANGE_LABEL";
export const SAVE_VALUES = "SAVE_VALUES";
export const CANCEL = "CANCEL";
export const GET_VALUES = "GET_VALUES";
